name: AWS OIDC Connection Test

on:
    push:
        branches:
            - "feat/*"

permissions:
    id-token: write
    contents: read

jobs:
    aws-oidc-test:
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Dump OIDC token sub
              run: |
                  TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                  "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com")
                  echo "OIDC sub claim:"
                  echo "$TOKEN" | jq -r '.sub'

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Test AWS Connection
              run: aws sts get-caller-identity
